# Generated by Django 4.0.6 on 2022-08-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chats',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
